### ISSUE TITLE
Aachen evaluation issue 

### ISSUE THREAD

**Issue by JingruiYu** [ethz-asl/hfnet#28]
Hello! Excellent work!

I was trying to follow the instruction of the Aachen localization part but run into trouble.

Running the command

> python3 hfnet/export_predictions.py hfnet/configs/hfnet_export_aachen_db.yaml superpoint/aachen --exper_name hfnet --keys keypoints,scores,local_descriptor_map

Error

>[02/04/2020 09:46:31 INFO] Starting to build databases: global: True, local: True
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "hfnet/evaluate_aachen.py", line 130, in <module>
    loc = Localization('aachen', args.model, config, build_db=args.build_db)
  File "/home/yujr/hfnet-master/hfnet/evaluation/localization.py", line 67, in __init__
    config_local=None if ok_local else config['local'])
  File "/home/yujr/hfnet-master/hfnet/evaluation/utils/db_management.py", line 70, in build_localization_dbs
    data['image'], data['name'], **config_global)
  File "/home/yujr/hfnet-master/hfnet/evaluation/loaders.py", line 81, in export_loader
    with np.load(path) as p:
  File "/home/yujr/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/yujr/hfnet-master/Exper/exports/hfnet/aachen/db/410.npz'

I am wondering where is the '410.npz' file?

By the way, I also tried to run the 'export_predictions.py', and here is part of the log,

> [02/04/2020 10:11:40 INFO] Restoring parameters from /home/yujr/hfnet-master/Exper/hfnet/model.ckpt-83096
2020-02-04 10:11:44.478406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-02-04 10:11:44.478482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-04 10:11:44.478502: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-02-04 10:11:44.478508: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-02-04 10:11:44.478698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3265 MB memory) -> physical GPU (device: 0, name: GeForce GTX 950M, pci bus id: 0000:01:00.0, compute capability: 5.0)
0it [00:00, ?it/s]2020-02-04 10:11:46.762573: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-02-04 10:11:46.785398: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
1it [00:02,  2.73s/it]2020-02-04 10:11:48.294971: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-02-04 10:11:48.317945: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2it [00:04,  2.37s/it]2020-02-04 10:11:49.836005: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-02-04 10:11:49.861545: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
4it [00:06,  1.56s/it]2020-02-04 10:11:51.696144: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-02-04 10:11:51.719383: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
6it [00:07,  1.33s/it]2020-02-04 10:11:53.328463: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.46GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2020-02-04 10:11:53.354390: W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.06GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
4479it [19:06,  3.91it/s]

Thank you!

**Comment by ssarahl** [comment]
@JingruiYu I think I ran into a similar problem at first, which I solved by instead running the command 

> hfnet/export_predictions.py hfnet/configs/hfnet_export_aachen_db.yaml aachen --exper_name hfnet --keys keypoints,scores,local_descriptor_map,global_descriptor

(aachen instead of superpoint/aachen, but also added global_descriptor) because the .npz files were going into `$DATA_PATH/exports/hfnet/superpoint/aachen` instead of `$DATA_PATH/exports/hfnet/aachen` as expected by the localization script.

**Comment by JingruiYu** [comment]
Thanks！It is useful.
