### ISSUE TITLE
CUDA error "device_side assert triggered" when run localization script

### ISSUE THREAD

**Issue by waitingjiang** [ethz-asl/hfnet#41]
Thanks for your great work! 

I am currently testing the basic pipeline, I downloaded aachen data ,  exported global, local descriptor and feature points from hfnet as described in hfnet/export_predictions.py, everything is just ok.

well, while I continued to run the  script "python3 hfnet/evaluate_aachen.py ", I got some CUDA-related error as below:
/tmp/pip-req-build-p5q91txh/aten/src/ATen/native/cuda/IndexKernel.cu:60: lambda [](int)->auto::operator()(int)->auto: block: [3,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "hfnet/evaluate_aachen.py", line 137, in <module>
    loc, queries, query_dataset, max_iter=args.max_iter)
  File "/home/jiangnicong/visual_place_recognition/hfnet/hfnet/evaluation/localization.py", line 215, in evaluate
    result, stats = loc.localize(query_info, query_data, debug=False)
  File "/home/jiangnicong/visual_place_recognition/hfnet/hfnet/evaluation/localization.py", line 160, in localize
    debug_dict=matches_data)
  File "/home/jiangnicong/visual_place_recognition/hfnet/hfnet/evaluation/utils/localization.py", line 96, in match_against_place
    query_desc, place_desc, ratio_thresh, labels=place_lms)
  File "/home/jiangnicong/visual_place_recognition/hfnet/hfnet/evaluation/utils/descriptors.py", line 111, in fast_matching
    if match_ok.any():
RuntimeError: CUDA error: device-side assert triggered

Could you please tell me what's the potential problems, you help will be great appreciated.
Thanks

**Comment by Skydes** [comment]
This is a PyTorch-related issue in [fast_matching](https://github.com/ethz-asl/hfnet/blob/master/hfnet/evaluation/utils/descriptors.py#L87). Verify your PyTorch and CUDA installations. I only tested this code with PyTorch 0.4.1 - it might fail with more recent versions.

**Comment by waitingjiang** [comment]
I found that the mistake, actually, comes from wrongly exporting super point features. Anyway, thank you so much for your kind reply. I will close the issue
